#! /bin/bash

# Create logs directory if it doesn't exist
mkdir -p logs

# Check if Node.js is installed
if ! which dotnet &> /dev/null; then
    echo "Error: dotnet is not installed."
    exit 1
fi

# Run
dotnet run 2>&1 | tee "logs/output_$(date +"%Y%m%d%H%M%S").txt"
