#! /bin/bash

# Always cd to the right dir
cd "$(dirname "${BASH_SOURCE[0]}")"

# Create logs directory if it doesn't exist
mkdir -p logs

# Run
php Satispay.php 2>&1 | tee "logs/output_$(date +"%Y%m%d%H%M%S").txt"
